import 'dart:io';
import 'package:flutter/material.dart';
import '../widgets/form_card.dart';
import '../widgets/custom_button.dart';
import '../services/database_service.dart';
import '../services/storage_service.dart';
import '../services/auth_service.dart';
import '../models/property.dart';
import 'home_screen.dart';

class PostDetailsScreen extends StatefulWidget {
  final List<File> images;

  const PostDetailsScreen({
    super.key,
    required this.images,
  });

  @override
  State<PostDetailsScreen> createState() => _PostDetailsScreenState();
}

class _PostDetailsScreenState extends State<PostDetailsScreen> {
  // Color palette
  static const Color primaryDark = Color(0xFF2C2C2C);
  static const Color lightGray = Color(0xFFF5F5F5);
  static const Color mediumGray = Color(0xFF9E9E9E);

  final PageController _pageController = PageController();
  int _currentImageIndex = 0;
  final _formKey = GlobalKey<FormState>();

  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _typeController = TextEditingController();
  final TextEditingController _priceController = TextEditingController();
  final TextEditingController _addressController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _areaController = TextEditingController();
  final TextEditingController _bedroomsController = TextEditingController();

  // Services
  final _databaseService = DatabaseService();
  final _storageService = StorageService();
  final _authService = AuthService();

  // State
  bool _isUploading = false;
  bool _hasGarden = false;
  bool _hasParking = false;

  @override
  void dispose() {
    _pageController.dispose();
    _nameController.dispose();
    _typeController.dispose();
    _priceController.dispose();
    _addressController.dispose();
    _descriptionController.dispose();
    _areaController.dispose();
    _bedroomsController.dispose();
    super.dispose();
  }

  Future<void> _handlePost() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Validate area and bedrooms
    if (_areaController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter the area (sqft)'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    if (_bedroomsController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter the number of bedrooms'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isUploading = true;
    });

    try {
      // Get current user
      final user = _authService.getCurrentUser();
      if (user == null) {
        throw Exception('User not authenticated');
      }

      // Upload images to Supabase Storage
      List<String> imageUrls = [];
      if (widget.images.isNotEmpty) {
        for (int i = 0; i < widget.images.length; i++) {
          final file = widget.images[i];
          final bytes = await file.readAsBytes();
          final fileName = '${DateTime.now().millisecondsSinceEpoch}_$i${file.path.split('.').last}';
          
          final imageUrl = await _storageService.uploadPropertyImage(
            bytes: bytes,
            fileName: fileName,
            userId: user.id,
          );
          imageUrls.add(imageUrl);
        }
      }

      // Create property object
      final property = Property(
        id: '', // Will be generated by database
        name: _nameController.text.trim(),
        address: _addressController.text.trim(),
        description: _descriptionController.text.trim(),
        price: double.parse(_priceController.text.trim()),
        area: int.parse(_areaController.text.trim()),
        bedrooms: int.parse(_bedroomsController.text.trim()),
        hasGarden: _hasGarden,
        hasParking: _hasParking,
        imageUrls: imageUrls,
        landlordId: user.id,
        status: 'approved', // Auto-approved
      );

      // Save to database
      await _databaseService.createProperty(property);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Property posted successfully! Awaiting approval.'),
            backgroundColor: Colors.green,
          ),
        );

        // Navigate back to home screen
        Navigator.of(context).pushAndRemoveUntil(
          MaterialPageRoute(
            builder: (context) => const HomeScreen(),
          ),
          (route) => false,
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error posting property: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isUploading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: lightGray,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: primaryDark),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: const Text(
          'Post Details',
          style: TextStyle(
            color: primaryDark,
            fontWeight: FontWeight.bold,
            fontSize: 18,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Image Carousel
              if (widget.images.isNotEmpty)
                Container(
                  height: 250,
                  width: double.infinity,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(15),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.1),
                        blurRadius: 8,
                        offset: const Offset(0, 2),
                      ),
                    ],
                  ),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(15),
                    child: Stack(
                      children: [
                        PageView.builder(
                          controller: _pageController,
                          itemCount: widget.images.length,
                          onPageChanged: (index) {
                            setState(() {
                              _currentImageIndex = index;
                            });
                          },
                          itemBuilder: (context, index) {
                            return Image.file(
                              widget.images[index],
                              fit: BoxFit.cover,
                            );
                          },
                        ),
                        // Dots Indicator
                        if (widget.images.length > 1)
                          Positioned(
                            bottom: 16,
                            left: 0,
                            right: 0,
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: List.generate(
                                widget.images.length,
                                (index) => Container(
                                  width: 8,
                                  height: 8,
                                  margin: const EdgeInsets.symmetric(horizontal: 4),
                                  decoration: BoxDecoration(
                                    shape: BoxShape.circle,
                                    color: _currentImageIndex == index
                                        ? Colors.white
                                        : Colors.white.withOpacity(0.5),
                                  ),
                                ),
                              ),
                            ),
                          ),
                      ],
                    ),
                  ),
                ),

              const SizedBox(height: 24),

              // Form Fields
              FormCard(
                backgroundColor: Colors.white,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildTextField(
                      controller: _nameController,
                      label: 'Name',
                      hint: 'Real-estate name',
                      icon: Icons.home,
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      controller: _typeController,
                      label: 'Type',
                      hint: 'Real-estate type',
                      icon: Icons.category,
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      controller: _priceController,
                      label: 'Price',
                      hint: 'Real-estate price',
                      icon: Icons.attach_money,
                      keyboardType: TextInputType.number,
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      controller: _areaController,
                      label: 'Area (sqft)',
                      hint: 'Area in square feet',
                      icon: Icons.square_foot,
                      keyboardType: TextInputType.number,
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      controller: _bedroomsController,
                      label: 'Bedrooms',
                      hint: 'Number of bedrooms',
                      icon: Icons.bed,
                      keyboardType: TextInputType.number,
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      controller: _addressController,
                      label: 'Address',
                      hint: 'Real-estate address',
                      icon: Icons.location_on,
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      controller: _descriptionController,
                      label: 'Description',
                      hint: 'Description',
                      icon: Icons.description,
                      maxLines: 4,
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 24),

              // Feature Tags
              const Text(
                'Features',
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                  color: primaryDark,
                ),
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  _buildFeatureTag('Garden', _hasGarden, () {
                    setState(() {
                      _hasGarden = !_hasGarden;
                    });
                  }),
                  const SizedBox(width: 12),
                  _buildFeatureTag('Parking', _hasParking, () {
                    setState(() {
                      _hasParking = !_hasParking;
                    });
                  }),
                ],
              ),

              const SizedBox(height: 32),

              // Post Button
              CustomButton(
                text: _isUploading ? 'Posting...' : 'Post',
                onPressed: _isUploading
                    ? () {}
                    : () {
                        _handlePost();
                      },
                backgroundColor: primaryDark,
                borderRadius: 15,
              ),

              const SizedBox(height: 16),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    required IconData icon,
    TextInputType? keyboardType,
    int maxLines = 1,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      maxLines: maxLines,
      decoration: InputDecoration(
        labelText: label,
        hintText: hint,
        prefixIcon: Icon(icon, color: primaryDark),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(15),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(15),
          borderSide: BorderSide(
            color: mediumGray.withOpacity(0.3),
          ),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(15),
          borderSide: const BorderSide(
            color: primaryDark,
            width: 2,
          ),
        ),
        filled: true,
        fillColor: lightGray,
      ),
      validator: (value) {
        if (value == null || value.trim().isEmpty) {
          return 'This field is required';
        }
        return null;
      },
    );
  }

  Widget _buildFeatureTag(String label, bool isSelected, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
        decoration: BoxDecoration(
          color: isSelected ? primaryDark : Colors.white,
          borderRadius: BorderRadius.circular(25),
          border: Border.all(
            color: isSelected ? primaryDark : mediumGray.withOpacity(0.3),
          ),
        ),
        child: Text(
          label,
          style: TextStyle(
            color: isSelected ? Colors.white : primaryDark,
            fontWeight: FontWeight.w600,
            fontSize: 14,
          ),
        ),
      ),
    );
  }
}

